### PR TITLE
Default to top 100 barcodes if not enough pass the threshold.

### PR DESCRIPTION
**Pull request by roryk**

### CODE REVIEW

**Comment by vals** [comment]
Wait, how does the threshold work? Do you just require a cutoff in the number of reads?

I can merge these, but there is a better way to select which barcodes to use, which I guess would be useful to automatically put in.

It seems to always be the case that if you look at log(n_reads) as a function of log(rank(n_reads)) you get this:

image
image
image

The red line indicates the number of cells as reported by the authors of the data sets. The last one seems to be wrong, yes.

I'm thinking that doing some kind of curve-fitting of (log(rank(n_reads)), log(n_reads)) could identify the correct number of cellular barcodes in the data.

**Comment by roryk** [comment]
Thanks Valentine, that looks like a nice solution. Some inDrop data I am looking at now doesn't seem to have this characteristic, but I haven't figured out if the data is crap or not. 
sp 08iz-cma

**Comment by vals** [comment]
The third of my figures is inDrop, if that helps any...

**Comment by roryk** [comment]
Thanks @vals, I reverted this commit.

**Pull request closed without merging**
