### PR TITLE
Batch kallisto transformation writes.

### PR DESCRIPTION
**Pull request by roryk**
Hi Valentine,

Hope you are well. This speeds up the kallisto transformation about 20x on some test data-- opening and closing file handles constantly wasn't a good plan.

### CODE REVIEW

**Comment by vals** [comment]
Yea this is an issue I have with the Kallisto approach of requiring demultiplexed files.

How many files do you usually open? Do you have some way of handling how many things are opening? When I worked on Illumina demultiplexing I ran in to OS level restrictions on the number of open files.

We have a dataset with 75.000 cells, how would it react to this? There should probably be a bit of documentation about limitations and so.

**Comment by roryk** [comment]
Hi Valentine,

Thanks-- the reads for each cell are accumulated by cellular barcode in a dict until it has kept 10,000,000 reads, then it opens a file for each barcode and appends to it, so there isn't ever more than one barcode file handle open at a given time. I ran it on a set that has over 100,000 barcodes in it and it works ok.

**Comment by roryk** [comment]
I'll update the documentation in a separate pull request, and add some more documentation for the command line options that are undocumented as well.

**Comment by roryk** [comment]
I updated the documentation; I think the caveat for open file handles isn't necessary, since we only open one at a time writing in batch mode so we shouldn't run into that problem.

**Comment by vals** [comment]
Thanks for the explanation. Then there shouldn't be any issues.

**Pull request merged**
