### PR TITLE
umi-tools compatability

### PR DESCRIPTION
**Pull request by MarinusVL**
Hi Rory,

We've been using umis for our single cell RNAseq and really like it and
made some modification to it. We'll be putting the pipeline on github
and wanted to ask you if you have any preference how to put the umis
branch up or if you would perhaps include our changes in the master
branch. I'll briefly describe our pipeline, and the additions to umis.
1. celseq2 reads
2. umis fastqtransform
3. umis cb_filter
4. umis sb_filter (new function to correct the sample reads with nedit 1
to the true sample barcode, blc2fastq demuxes with nedit1 but doesn't correct)
5. umis mb_filter (new function to remove any umi reads with non ACGT
bases , N bases in our case)
6. umis add_uid (new function to add unique identifier (UID) tag to read
name consisting of the concatenation of SB CB MB, this is needed to
allow UMI-tools dedup on bam files with multiple cells/samples
7. align STAR
8. count metafeatures with featurecounts and transfer geneID to bam file
with XF:Z: tag (htseq can also do this but is slower)
9. UMI-tools dedup on a per gene basis using the geneID tag in the bam
file
10. expression matrix from bam file We're now using our own script to
get the expression matrix. if you would make umis tag_count compatible
with this pipeline, I suggest having both the sample and cell barcode in
the column headers instead of only the cell barcode, and allow
tagcounts to count the XF:Z: tags.

We also changed the barcodehash in umis to include N bases so that those
get also corrected.

There seems to be interest in such a pipeline as there are quite a few
request in the umi-tools comment section on how to preprocess
single-cell reads. umis is ideal for this and that is why we modified
it. The bc-bio pipeline currently only works with the pseudo aligners,
which don't work so well on umi end tagged libraries, so I think an
option to do traditional alignment/gene counting in the bc-bio pipeline
would be useful. (as least we would have used that if it was available)

I'm mostly running experiments so this is my first github project so not
really sure how to best branch umis or whatever. I think our preferred
way would be to have our changes in the umis master branch and maybe a
link on the bc-bio scRANseq page to our pipeline for people that would
like to do traditional gene alignement/counting. But let us know what
you prefer. We could also just have the branch at the umis page or our page.

https://github.com/MarinusVL/scRNApipe

in the pull request the umis.py and barcodes.py, they work on our
cellseq2 data but I think there may be some bugs for data in other
formats, (without sample barcodes or with multiple cell barcodes most
likely)

Thanks, Marinus

### CODE REVIEW

**Comment by vals** [comment]
Hi Marinus,

If you have modification or options added to `umis` which are useful it would be great to add them!

We have one CEL-Seq2 transform here: https://github.com/vals/umis/tree/master/examples/CEL-Seq2 , but if you have another one, more examples are better!

the filters you are including here seems great and useful. 

The middle step of mapping to transcripts / genes can be done in any way you like of course, but what kind of problems are you seeing using RapMap? We've used RapMap for this purpose for >30 different data sets so far and it's worked well for us.

Is there a particular issue using `umis tagcount` rather than going through featureCounts?

If you're using UMI-tools for counting, I don't really see the point of including it here. You can do pre-processing with `umis`, map with some tool, then count with another.

**Comment by MarinusVL** [comment]
Hi Valentine,

Great, if you could put them in the master, hopefully more people will find
these useful and having an easy conda install is also nice.

here is our CEL-Seq2 json transform, it adds sample barcodes in
demultiplexed reads by blc2fastq

{
  "read1": "(?P<name>@.*)
.:*.:*.:(?P<SB>.*).*\\n(?P<MB>.{6})(?P<CB>.{6})(.*)\\n\\+(.*)\\n(.*)\\n",
  "read2": "(?P<name>@.*) .*\\n(?P<seq>.*)\\n\\+\\n(?P<qual>.*)\\n"
}

I definitely see the advantages for using RapMap for full length RNAseq,
especially since bootstrapping can then provide a measure of technical
variance. On strongly 5' or 3' end biased libraries (as ours are) these
nice tricks, at least theoretically, don't work so well. We didn't do any
proper comparisons but chose to do full genome + transcriptome alignment
with STAR and traditional gene counting and umi-tools deduplication, this
works very well for us, and better than the original celseq pipeline.

as for using featureCounts instead of tagcount, we're using umi-tools at
the gene level, this however requires tagging the bam with the gene_id so
that's why we run featurecounts before umi deduplication.

best regards, Marinus




2017-05-04 5:15 GMT-07:00 Valentine Svensson <notifications@github.com>:

**Comment by vals** [comment]
Hi Marinus,

Well, I won't argue too much :p, but we _only_ use RapMap for 3' / 5' tag counting, and do this on the gene level by providing a gene map to `umis tagcount`. We compared it to STAR + HTSeq-count a long time ago and preferred this approach. (HTSeq in particular removes multimapping reads, which is an issue when the mRNA tag is short, as many of the early datasets were.)

Anyway, thanks for the improvements!

Would it be possible for you to add your transform and 10 reads of fastqs in your format to a new directory in the `Examples` directory? The 10 reads can be fake if you want, just as long as they are in your format. We like to have representatives of the different layouts people use, and at some point catalog them.

**Comment by MarinusVL** [comment]
Hi Valentine, sure, will add the fastqs, good to know that RapMap is doing
so well on these reads, everyone happy. Cheers, Marijn

2017-05-05 2:16 GMT-07:00 Valentine Svensson <notifications@github.com>:

**Comment by vals** [comment]
Awesome! Thank's a lot for sharing your code!

**Pull request merged**
